version: 0.2

env:
    variables:
        MY_AWS_REGION: "us-east-1"


phases: 
    install:
        runtime-versions:
            python: 3.11
        commands:
            - echo "install started"
            - echo "Running on $MY_AWS_REGION"
            - echo "install completed"
    pre_build:
        commands: 
            - echo "pre_build started"
            - echo "pre_build completed"
    build:
        commands:
            - echo "build started"
            - echo "build completed"
    post_build:
        commands:
            - echo "post_build started"
            - echo "post_build completed"