# Copyright (c) 2023 Mikheil Tabidze
BASE_URL = "http://127.0.0.1:8000/"
V1_EP = BASE_URL + "v1/"
BLING_EP = V1_EP + "bling/"
BLING_RESPONSES_EP = BLING_EP + "responses/"
OPEN_AI_EP = V1_EP + "openai/"
OPEN_AI_CHAT_COMPLETIONS_EP = OPEN_AI_EP + "chat/completions/"
OPEN_AI_TOKENIZE_EP = OPEN_AI_EP + "tokenize/"
HEALTH_CHECK_EP = V1_EP + "health-check/"
LIVENESS_EP = HEALTH_CHECK_EP + "liveness/"
READINESS_EP = HEALTH_CHECK_EP + "readiness/"
